/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecordesRouteImport } from './routes/recordes'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as ModalidadesRouteImport } from './routes/modalidades'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscricoesRouteImport } from './routes/inscricoes'
import { Route as FilieSeRouteImport } from './routes/filie-se'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ClubesRouteImport } from './routes/clubes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticiasIdRouteImport } from './routes/noticias.$id'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminTransparenciaRouteImport } from './routes/_authenticated/admin/transparencia'
import { Route as AuthenticatedAdminRecordesRouteImport } from './routes/_authenticated/admin/recordes'
import { Route as AuthenticatedAdminRankingsRouteImport } from './routes/_authenticated/admin/rankings'
import { Route as AuthenticatedAdminPermissoesRouteImport } from './routes/_authenticated/admin/permissoes'
import { Route as AuthenticatedAdminPerfilRouteImport } from './routes/_authenticated/admin/perfil'
import { Route as AuthenticatedAdminParceirosRouteImport } from './routes/_authenticated/admin/parceiros'
import { Route as AuthenticatedAdminNotificacoesRouteImport } from './routes/_authenticated/admin/notificacoes'
import { Route as AuthenticatedAdminNoticiasRouteImport } from './routes/_authenticated/admin/noticias'
import { Route as AuthenticatedAdminModalidadesRouteImport } from './routes/_authenticated/admin/modalidades'
import { Route as AuthenticatedAdminMensagensRouteImport } from './routes/_authenticated/admin/mensagens'
import { Route as AuthenticatedAdminHistoricoRouteImport } from './routes/_authenticated/admin/historico'
import { Route as AuthenticatedAdminFiliacoesRouteImport } from './routes/_authenticated/admin/filiacoes'
import { Route as AuthenticatedAdminEventosPdfsRouteImport } from './routes/_authenticated/admin/eventos-pdfs'
import { Route as AuthenticatedAdminEventosRouteImport } from './routes/_authenticated/admin/eventos'
import { Route as AuthenticatedAdminDiretoresRouteImport } from './routes/_authenticated/admin/diretores'
import { Route as AuthenticatedAdminCursosRouteImport } from './routes/_authenticated/admin/cursos'
import { Route as AuthenticatedAdminClubesRouteImport } from './routes/_authenticated/admin/clubes'
import { Route as AuthenticatedAdminCategoriasModalidadesRouteImport } from './routes/_authenticated/admin/categorias-modalidades'
import { Route as AuthenticatedAdminBannerRouteImport } from './routes/_authenticated/admin/banner'

const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordesRoute = RecordesRouteImport.update({
  id: '/recordes',
  path: '/recordes',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const ModalidadesRoute = ModalidadesRouteImport.update({
  id: '/modalidades',
  path: '/modalidades',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricoesRoute = InscricoesRouteImport.update({
  id: '/inscricoes',
  path: '/inscricoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FilieSeRoute = FilieSeRouteImport.update({
  id: '/filie-se',
  path: '/filie-se',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubesRoute = ClubesRouteImport.update({
  id: '/clubes',
  path: '/clubes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIdRoute = NoticiasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NoticiasRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTransparenciaRoute =
  AuthenticatedAdminTransparenciaRouteImport.update({
    id: '/transparencia',
    path: '/transparencia',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRecordesRoute =
  AuthenticatedAdminRecordesRouteImport.update({
    id: '/recordes',
    path: '/recordes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRankingsRoute =
  AuthenticatedAdminRankingsRouteImport.update({
    id: '/rankings',
    path: '/rankings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPermissoesRoute =
  AuthenticatedAdminPermissoesRouteImport.update({
    id: '/permissoes',
    path: '/permissoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPerfilRoute =
  AuthenticatedAdminPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminParceirosRoute =
  AuthenticatedAdminParceirosRouteImport.update({
    id: '/parceiros',
    path: '/parceiros',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificacoesRoute =
  AuthenticatedAdminNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNoticiasRoute =
  AuthenticatedAdminNoticiasRouteImport.update({
    id: '/noticias',
    path: '/noticias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModalidadesRoute =
  AuthenticatedAdminModalidadesRouteImport.update({
    id: '/modalidades',
    path: '/modalidades',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMensagensRoute =
  AuthenticatedAdminMensagensRouteImport.update({
    id: '/mensagens',
    path: '/mensagens',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHistoricoRoute =
  AuthenticatedAdminHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFiliacoesRoute =
  AuthenticatedAdminFiliacoesRouteImport.update({
    id: '/filiacoes',
    path: '/filiacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosPdfsRoute =
  AuthenticatedAdminEventosPdfsRouteImport.update({
    id: '/eventos-pdfs',
    path: '/eventos-pdfs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosRoute =
  AuthenticatedAdminEventosRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDiretoresRoute =
  AuthenticatedAdminDiretoresRouteImport.update({
    id: '/diretores',
    path: '/diretores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCursosRoute =
  AuthenticatedAdminCursosRouteImport.update({
    id: '/cursos',
    path: '/cursos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClubesRoute =
  AuthenticatedAdminClubesRouteImport.update({
    id: '/clubes',
    path: '/clubes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriasModalidadesRoute =
  AuthenticatedAdminCategoriasModalidadesRouteImport.update({
    id: '/categorias-modalidades',
    path: '/categorias-modalidades',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBannerRoute =
  AuthenticatedAdminBannerRouteImport.update({
    id: '/banner',
    path: '/banner',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/clubes': typeof ClubesRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/eventos': typeof EventosRoute
  '/filie-se': typeof FilieSeRoute
  '/inscricoes': typeof InscricoesRoute
  '/login': typeof LoginRoute
  '/modalidades': typeof ModalidadesRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/recordes': typeof RecordesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/transparencia': typeof TransparenciaRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/noticias/$id': typeof NoticiasIdRoute
  '/admin/banner': typeof AuthenticatedAdminBannerRoute
  '/admin/categorias-modalidades': typeof AuthenticatedAdminCategoriasModalidadesRoute
  '/admin/clubes': typeof AuthenticatedAdminClubesRoute
  '/admin/cursos': typeof AuthenticatedAdminCursosRoute
  '/admin/diretores': typeof AuthenticatedAdminDiretoresRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/eventos-pdfs': typeof AuthenticatedAdminEventosPdfsRoute
  '/admin/filiacoes': typeof AuthenticatedAdminFiliacoesRoute
  '/admin/historico': typeof AuthenticatedAdminHistoricoRoute
  '/admin/mensagens': typeof AuthenticatedAdminMensagensRoute
  '/admin/modalidades': typeof AuthenticatedAdminModalidadesRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/parceiros': typeof AuthenticatedAdminParceirosRoute
  '/admin/perfil': typeof AuthenticatedAdminPerfilRoute
  '/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/admin/rankings': typeof AuthenticatedAdminRankingsRoute
  '/admin/recordes': typeof AuthenticatedAdminRecordesRoute
  '/admin/transparencia': typeof AuthenticatedAdminTransparenciaRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/clubes': typeof ClubesRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/eventos': typeof EventosRoute
  '/filie-se': typeof FilieSeRoute
  '/inscricoes': typeof InscricoesRoute
  '/login': typeof LoginRoute
  '/modalidades': typeof ModalidadesRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/recordes': typeof RecordesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/transparencia': typeof TransparenciaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/noticias/$id': typeof NoticiasIdRoute
  '/admin/banner': typeof AuthenticatedAdminBannerRoute
  '/admin/categorias-modalidades': typeof AuthenticatedAdminCategoriasModalidadesRoute
  '/admin/clubes': typeof AuthenticatedAdminClubesRoute
  '/admin/cursos': typeof AuthenticatedAdminCursosRoute
  '/admin/diretores': typeof AuthenticatedAdminDiretoresRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/eventos-pdfs': typeof AuthenticatedAdminEventosPdfsRoute
  '/admin/filiacoes': typeof AuthenticatedAdminFiliacoesRoute
  '/admin/historico': typeof AuthenticatedAdminHistoricoRoute
  '/admin/mensagens': typeof AuthenticatedAdminMensagensRoute
  '/admin/modalidades': typeof AuthenticatedAdminModalidadesRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/parceiros': typeof AuthenticatedAdminParceirosRoute
  '/admin/perfil': typeof AuthenticatedAdminPerfilRoute
  '/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/admin/rankings': typeof AuthenticatedAdminRankingsRoute
  '/admin/recordes': typeof AuthenticatedAdminRecordesRoute
  '/admin/transparencia': typeof AuthenticatedAdminTransparenciaRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/clubes': typeof ClubesRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/eventos': typeof EventosRoute
  '/filie-se': typeof FilieSeRoute
  '/inscricoes': typeof InscricoesRoute
  '/login': typeof LoginRoute
  '/modalidades': typeof ModalidadesRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/recordes': typeof RecordesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/transparencia': typeof TransparenciaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/noticias/$id': typeof NoticiasIdRoute
  '/_authenticated/admin/banner': typeof AuthenticatedAdminBannerRoute
  '/_authenticated/admin/categorias-modalidades': typeof AuthenticatedAdminCategoriasModalidadesRoute
  '/_authenticated/admin/clubes': typeof AuthenticatedAdminClubesRoute
  '/_authenticated/admin/cursos': typeof AuthenticatedAdminCursosRoute
  '/_authenticated/admin/diretores': typeof AuthenticatedAdminDiretoresRoute
  '/_authenticated/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/_authenticated/admin/eventos-pdfs': typeof AuthenticatedAdminEventosPdfsRoute
  '/_authenticated/admin/filiacoes': typeof AuthenticatedAdminFiliacoesRoute
  '/_authenticated/admin/historico': typeof AuthenticatedAdminHistoricoRoute
  '/_authenticated/admin/mensagens': typeof AuthenticatedAdminMensagensRoute
  '/_authenticated/admin/modalidades': typeof AuthenticatedAdminModalidadesRoute
  '/_authenticated/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/_authenticated/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/_authenticated/admin/parceiros': typeof AuthenticatedAdminParceirosRoute
  '/_authenticated/admin/perfil': typeof AuthenticatedAdminPerfilRoute
  '/_authenticated/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/_authenticated/admin/rankings': typeof AuthenticatedAdminRankingsRoute
  '/_authenticated/admin/recordes': typeof AuthenticatedAdminRecordesRoute
  '/_authenticated/admin/transparencia': typeof AuthenticatedAdminTransparenciaRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/clubes'
    | '/contato'
    | '/cursos'
    | '/eventos'
    | '/filie-se'
    | '/inscricoes'
    | '/login'
    | '/modalidades'
    | '/noticias'
    | '/rankings'
    | '/recordes'
    | '/reset-password'
    | '/sobre'
    | '/transparencia'
    | '/admin'
    | '/perfil'
    | '/noticias/$id'
    | '/admin/banner'
    | '/admin/categorias-modalidades'
    | '/admin/clubes'
    | '/admin/cursos'
    | '/admin/diretores'
    | '/admin/eventos'
    | '/admin/eventos-pdfs'
    | '/admin/filiacoes'
    | '/admin/historico'
    | '/admin/mensagens'
    | '/admin/modalidades'
    | '/admin/noticias'
    | '/admin/notificacoes'
    | '/admin/parceiros'
    | '/admin/perfil'
    | '/admin/permissoes'
    | '/admin/rankings'
    | '/admin/recordes'
    | '/admin/transparencia'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/clubes'
    | '/contato'
    | '/cursos'
    | '/eventos'
    | '/filie-se'
    | '/inscricoes'
    | '/login'
    | '/modalidades'
    | '/noticias'
    | '/rankings'
    | '/recordes'
    | '/reset-password'
    | '/sobre'
    | '/transparencia'
    | '/perfil'
    | '/noticias/$id'
    | '/admin/banner'
    | '/admin/categorias-modalidades'
    | '/admin/clubes'
    | '/admin/cursos'
    | '/admin/diretores'
    | '/admin/eventos'
    | '/admin/eventos-pdfs'
    | '/admin/filiacoes'
    | '/admin/historico'
    | '/admin/mensagens'
    | '/admin/modalidades'
    | '/admin/noticias'
    | '/admin/notificacoes'
    | '/admin/parceiros'
    | '/admin/perfil'
    | '/admin/permissoes'
    | '/admin/rankings'
    | '/admin/recordes'
    | '/admin/transparencia'
    | '/admin/usuarios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/clubes'
    | '/contato'
    | '/cursos'
    | '/eventos'
    | '/filie-se'
    | '/inscricoes'
    | '/login'
    | '/modalidades'
    | '/noticias'
    | '/rankings'
    | '/recordes'
    | '/reset-password'
    | '/sobre'
    | '/transparencia'
    | '/_authenticated/admin'
    | '/_authenticated/perfil'
    | '/noticias/$id'
    | '/_authenticated/admin/banner'
    | '/_authenticated/admin/categorias-modalidades'
    | '/_authenticated/admin/clubes'
    | '/_authenticated/admin/cursos'
    | '/_authenticated/admin/diretores'
    | '/_authenticated/admin/eventos'
    | '/_authenticated/admin/eventos-pdfs'
    | '/_authenticated/admin/filiacoes'
    | '/_authenticated/admin/historico'
    | '/_authenticated/admin/mensagens'
    | '/_authenticated/admin/modalidades'
    | '/_authenticated/admin/noticias'
    | '/_authenticated/admin/notificacoes'
    | '/_authenticated/admin/parceiros'
    | '/_authenticated/admin/perfil'
    | '/_authenticated/admin/permissoes'
    | '/_authenticated/admin/rankings'
    | '/_authenticated/admin/recordes'
    | '/_authenticated/admin/transparencia'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  ClubesRoute: typeof ClubesRoute
  ContatoRoute: typeof ContatoRoute
  CursosRoute: typeof CursosRoute
  EventosRoute: typeof EventosRoute
  FilieSeRoute: typeof FilieSeRoute
  InscricoesRoute: typeof InscricoesRoute
  LoginRoute: typeof LoginRoute
  ModalidadesRoute: typeof ModalidadesRoute
  NoticiasRoute: typeof NoticiasRouteWithChildren
  RankingsRoute: typeof RankingsRoute
  RecordesRoute: typeof RecordesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SobreRoute: typeof SobreRoute
  TransparenciaRoute: typeof TransparenciaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordes': {
      id: '/recordes'
      path: '/recordes'
      fullPath: '/recordes'
      preLoaderRoute: typeof RecordesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modalidades': {
      id: '/modalidades'
      path: '/modalidades'
      fullPath: '/modalidades'
      preLoaderRoute: typeof ModalidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricoes': {
      id: '/inscricoes'
      path: '/inscricoes'
      fullPath: '/inscricoes'
      preLoaderRoute: typeof InscricoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filie-se': {
      id: '/filie-se'
      path: '/filie-se'
      fullPath: '/filie-se'
      preLoaderRoute: typeof FilieSeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubes': {
      id: '/clubes'
      path: '/clubes'
      fullPath: '/clubes'
      preLoaderRoute: typeof ClubesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$id': {
      id: '/noticias/$id'
      path: '/$id'
      fullPath: '/noticias/$id'
      preLoaderRoute: typeof NoticiasIdRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/transparencia': {
      id: '/_authenticated/admin/transparencia'
      path: '/transparencia'
      fullPath: '/admin/transparencia'
      preLoaderRoute: typeof AuthenticatedAdminTransparenciaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/recordes': {
      id: '/_authenticated/admin/recordes'
      path: '/recordes'
      fullPath: '/admin/recordes'
      preLoaderRoute: typeof AuthenticatedAdminRecordesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rankings': {
      id: '/_authenticated/admin/rankings'
      path: '/rankings'
      fullPath: '/admin/rankings'
      preLoaderRoute: typeof AuthenticatedAdminRankingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/permissoes': {
      id: '/_authenticated/admin/permissoes'
      path: '/permissoes'
      fullPath: '/admin/permissoes'
      preLoaderRoute: typeof AuthenticatedAdminPermissoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/perfil': {
      id: '/_authenticated/admin/perfil'
      path: '/perfil'
      fullPath: '/admin/perfil'
      preLoaderRoute: typeof AuthenticatedAdminPerfilRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/parceiros': {
      id: '/_authenticated/admin/parceiros'
      path: '/parceiros'
      fullPath: '/admin/parceiros'
      preLoaderRoute: typeof AuthenticatedAdminParceirosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notificacoes': {
      id: '/_authenticated/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AuthenticatedAdminNotificacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/noticias': {
      id: '/_authenticated/admin/noticias'
      path: '/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AuthenticatedAdminNoticiasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/modalidades': {
      id: '/_authenticated/admin/modalidades'
      path: '/modalidades'
      fullPath: '/admin/modalidades'
      preLoaderRoute: typeof AuthenticatedAdminModalidadesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mensagens': {
      id: '/_authenticated/admin/mensagens'
      path: '/mensagens'
      fullPath: '/admin/mensagens'
      preLoaderRoute: typeof AuthenticatedAdminMensagensRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/historico': {
      id: '/_authenticated/admin/historico'
      path: '/historico'
      fullPath: '/admin/historico'
      preLoaderRoute: typeof AuthenticatedAdminHistoricoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/filiacoes': {
      id: '/_authenticated/admin/filiacoes'
      path: '/filiacoes'
      fullPath: '/admin/filiacoes'
      preLoaderRoute: typeof AuthenticatedAdminFiliacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos-pdfs': {
      id: '/_authenticated/admin/eventos-pdfs'
      path: '/eventos-pdfs'
      fullPath: '/admin/eventos-pdfs'
      preLoaderRoute: typeof AuthenticatedAdminEventosPdfsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos': {
      id: '/_authenticated/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AuthenticatedAdminEventosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/diretores': {
      id: '/_authenticated/admin/diretores'
      path: '/diretores'
      fullPath: '/admin/diretores'
      preLoaderRoute: typeof AuthenticatedAdminDiretoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cursos': {
      id: '/_authenticated/admin/cursos'
      path: '/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AuthenticatedAdminCursosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clubes': {
      id: '/_authenticated/admin/clubes'
      path: '/clubes'
      fullPath: '/admin/clubes'
      preLoaderRoute: typeof AuthenticatedAdminClubesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias-modalidades': {
      id: '/_authenticated/admin/categorias-modalidades'
      path: '/categorias-modalidades'
      fullPath: '/admin/categorias-modalidades'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasModalidadesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/banner': {
      id: '/_authenticated/admin/banner'
      path: '/banner'
      fullPath: '/admin/banner'
      preLoaderRoute: typeof AuthenticatedAdminBannerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBannerRoute: typeof AuthenticatedAdminBannerRoute
  AuthenticatedAdminCategoriasModalidadesRoute: typeof AuthenticatedAdminCategoriasModalidadesRoute
  AuthenticatedAdminClubesRoute: typeof AuthenticatedAdminClubesRoute
  AuthenticatedAdminCursosRoute: typeof AuthenticatedAdminCursosRoute
  AuthenticatedAdminDiretoresRoute: typeof AuthenticatedAdminDiretoresRoute
  AuthenticatedAdminEventosRoute: typeof AuthenticatedAdminEventosRoute
  AuthenticatedAdminEventosPdfsRoute: typeof AuthenticatedAdminEventosPdfsRoute
  AuthenticatedAdminFiliacoesRoute: typeof AuthenticatedAdminFiliacoesRoute
  AuthenticatedAdminHistoricoRoute: typeof AuthenticatedAdminHistoricoRoute
  AuthenticatedAdminMensagensRoute: typeof AuthenticatedAdminMensagensRoute
  AuthenticatedAdminModalidadesRoute: typeof AuthenticatedAdminModalidadesRoute
  AuthenticatedAdminNoticiasRoute: typeof AuthenticatedAdminNoticiasRoute
  AuthenticatedAdminNotificacoesRoute: typeof AuthenticatedAdminNotificacoesRoute
  AuthenticatedAdminParceirosRoute: typeof AuthenticatedAdminParceirosRoute
  AuthenticatedAdminPerfilRoute: typeof AuthenticatedAdminPerfilRoute
  AuthenticatedAdminPermissoesRoute: typeof AuthenticatedAdminPermissoesRoute
  AuthenticatedAdminRankingsRoute: typeof AuthenticatedAdminRankingsRoute
  AuthenticatedAdminRecordesRoute: typeof AuthenticatedAdminRecordesRoute
  AuthenticatedAdminTransparenciaRoute: typeof AuthenticatedAdminTransparenciaRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBannerRoute: AuthenticatedAdminBannerRoute,
  AuthenticatedAdminCategoriasModalidadesRoute:
    AuthenticatedAdminCategoriasModalidadesRoute,
  AuthenticatedAdminClubesRoute: AuthenticatedAdminClubesRoute,
  AuthenticatedAdminCursosRoute: AuthenticatedAdminCursosRoute,
  AuthenticatedAdminDiretoresRoute: AuthenticatedAdminDiretoresRoute,
  AuthenticatedAdminEventosRoute: AuthenticatedAdminEventosRoute,
  AuthenticatedAdminEventosPdfsRoute: AuthenticatedAdminEventosPdfsRoute,
  AuthenticatedAdminFiliacoesRoute: AuthenticatedAdminFiliacoesRoute,
  AuthenticatedAdminHistoricoRoute: AuthenticatedAdminHistoricoRoute,
  AuthenticatedAdminMensagensRoute: AuthenticatedAdminMensagensRoute,
  AuthenticatedAdminModalidadesRoute: AuthenticatedAdminModalidadesRoute,
  AuthenticatedAdminNoticiasRoute: AuthenticatedAdminNoticiasRoute,
  AuthenticatedAdminNotificacoesRoute: AuthenticatedAdminNotificacoesRoute,
  AuthenticatedAdminParceirosRoute: AuthenticatedAdminParceirosRoute,
  AuthenticatedAdminPerfilRoute: AuthenticatedAdminPerfilRoute,
  AuthenticatedAdminPermissoesRoute: AuthenticatedAdminPermissoesRoute,
  AuthenticatedAdminRankingsRoute: AuthenticatedAdminRankingsRoute,
  AuthenticatedAdminRecordesRoute: AuthenticatedAdminRecordesRoute,
  AuthenticatedAdminTransparenciaRoute: AuthenticatedAdminTransparenciaRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface NoticiasRouteChildren {
  NoticiasIdRoute: typeof NoticiasIdRoute
}

const NoticiasRouteChildren: NoticiasRouteChildren = {
  NoticiasIdRoute: NoticiasIdRoute,
}

const NoticiasRouteWithChildren = NoticiasRoute._addFileChildren(
  NoticiasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroRoute: CadastroRoute,
  ClubesRoute: ClubesRoute,
  ContatoRoute: ContatoRoute,
  CursosRoute: CursosRoute,
  EventosRoute: EventosRoute,
  FilieSeRoute: FilieSeRoute,
  InscricoesRoute: InscricoesRoute,
  LoginRoute: LoginRoute,
  ModalidadesRoute: ModalidadesRoute,
  NoticiasRoute: NoticiasRouteWithChildren,
  RankingsRoute: RankingsRoute,
  RecordesRoute: RecordesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SobreRoute: SobreRoute,
  TransparenciaRoute: TransparenciaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
