/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as ModalidadesRouteImport } from './routes/modalidades'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscricoesRouteImport } from './routes/inscricoes'
import { Route as FilieSeRouteImport } from './routes/filie-se'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticiasIdRouteImport } from './routes/noticias.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminTransparenciaRouteImport } from './routes/_authenticated/admin/transparencia'
import { Route as AuthenticatedAdminNoticiasRouteImport } from './routes/_authenticated/admin/noticias'
import { Route as AuthenticatedAdminModalidadesRouteImport } from './routes/_authenticated/admin/modalidades'
import { Route as AuthenticatedAdminMensagensRouteImport } from './routes/_authenticated/admin/mensagens'
import { Route as AuthenticatedAdminFiliacoesRouteImport } from './routes/_authenticated/admin/filiacoes'
import { Route as AuthenticatedAdminEventosPdfsRouteImport } from './routes/_authenticated/admin/eventos-pdfs'
import { Route as AuthenticatedAdminEventosRouteImport } from './routes/_authenticated/admin/eventos'
import { Route as AuthenticatedAdminDiretoresRouteImport } from './routes/_authenticated/admin/diretores'
import { Route as AuthenticatedAdminCategoriasModalidadesRouteImport } from './routes/_authenticated/admin/categorias-modalidades'
import { Route as AuthenticatedAdminBannerRouteImport } from './routes/_authenticated/admin/banner'

const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const ModalidadesRoute = ModalidadesRouteImport.update({
  id: '/modalidades',
  path: '/modalidades',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricoesRoute = InscricoesRouteImport.update({
  id: '/inscricoes',
  path: '/inscricoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FilieSeRoute = FilieSeRouteImport.update({
  id: '/filie-se',
  path: '/filie-se',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIdRoute = NoticiasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NoticiasRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTransparenciaRoute =
  AuthenticatedAdminTransparenciaRouteImport.update({
    id: '/admin/transparencia',
    path: '/admin/transparencia',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNoticiasRoute =
  AuthenticatedAdminNoticiasRouteImport.update({
    id: '/admin/noticias',
    path: '/admin/noticias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminModalidadesRoute =
  AuthenticatedAdminModalidadesRouteImport.update({
    id: '/admin/modalidades',
    path: '/admin/modalidades',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMensagensRoute =
  AuthenticatedAdminMensagensRouteImport.update({
    id: '/admin/mensagens',
    path: '/admin/mensagens',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminFiliacoesRoute =
  AuthenticatedAdminFiliacoesRouteImport.update({
    id: '/admin/filiacoes',
    path: '/admin/filiacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEventosPdfsRoute =
  AuthenticatedAdminEventosPdfsRouteImport.update({
    id: '/admin/eventos-pdfs',
    path: '/admin/eventos-pdfs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEventosRoute =
  AuthenticatedAdminEventosRouteImport.update({
    id: '/admin/eventos',
    path: '/admin/eventos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDiretoresRoute =
  AuthenticatedAdminDiretoresRouteImport.update({
    id: '/admin/diretores',
    path: '/admin/diretores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCategoriasModalidadesRoute =
  AuthenticatedAdminCategoriasModalidadesRouteImport.update({
    id: '/admin/categorias-modalidades',
    path: '/admin/categorias-modalidades',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBannerRoute =
  AuthenticatedAdminBannerRouteImport.update({
    id: '/admin/banner',
    path: '/admin/banner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/eventos': typeof EventosRoute
  '/filie-se': typeof FilieSeRoute
  '/inscricoes': typeof InscricoesRoute
  '/login': typeof LoginRoute
  '/modalidades': typeof ModalidadesRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/transparencia': typeof TransparenciaRoute
  '/noticias/$id': typeof NoticiasIdRoute
  '/admin/banner': typeof AuthenticatedAdminBannerRoute
  '/admin/categorias-modalidades': typeof AuthenticatedAdminCategoriasModalidadesRoute
  '/admin/diretores': typeof AuthenticatedAdminDiretoresRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/eventos-pdfs': typeof AuthenticatedAdminEventosPdfsRoute
  '/admin/filiacoes': typeof AuthenticatedAdminFiliacoesRoute
  '/admin/mensagens': typeof AuthenticatedAdminMensagensRoute
  '/admin/modalidades': typeof AuthenticatedAdminModalidadesRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/admin/transparencia': typeof AuthenticatedAdminTransparenciaRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/eventos': typeof EventosRoute
  '/filie-se': typeof FilieSeRoute
  '/inscricoes': typeof InscricoesRoute
  '/login': typeof LoginRoute
  '/modalidades': typeof ModalidadesRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/transparencia': typeof TransparenciaRoute
  '/noticias/$id': typeof NoticiasIdRoute
  '/admin/banner': typeof AuthenticatedAdminBannerRoute
  '/admin/categorias-modalidades': typeof AuthenticatedAdminCategoriasModalidadesRoute
  '/admin/diretores': typeof AuthenticatedAdminDiretoresRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/eventos-pdfs': typeof AuthenticatedAdminEventosPdfsRoute
  '/admin/filiacoes': typeof AuthenticatedAdminFiliacoesRoute
  '/admin/mensagens': typeof AuthenticatedAdminMensagensRoute
  '/admin/modalidades': typeof AuthenticatedAdminModalidadesRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/admin/transparencia': typeof AuthenticatedAdminTransparenciaRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/contato': typeof ContatoRoute
  '/eventos': typeof EventosRoute
  '/filie-se': typeof FilieSeRoute
  '/inscricoes': typeof InscricoesRoute
  '/login': typeof LoginRoute
  '/modalidades': typeof ModalidadesRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/transparencia': typeof TransparenciaRoute
  '/noticias/$id': typeof NoticiasIdRoute
  '/_authenticated/admin/banner': typeof AuthenticatedAdminBannerRoute
  '/_authenticated/admin/categorias-modalidades': typeof AuthenticatedAdminCategoriasModalidadesRoute
  '/_authenticated/admin/diretores': typeof AuthenticatedAdminDiretoresRoute
  '/_authenticated/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/_authenticated/admin/eventos-pdfs': typeof AuthenticatedAdminEventosPdfsRoute
  '/_authenticated/admin/filiacoes': typeof AuthenticatedAdminFiliacoesRoute
  '/_authenticated/admin/mensagens': typeof AuthenticatedAdminMensagensRoute
  '/_authenticated/admin/modalidades': typeof AuthenticatedAdminModalidadesRoute
  '/_authenticated/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/_authenticated/admin/transparencia': typeof AuthenticatedAdminTransparenciaRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/eventos'
    | '/filie-se'
    | '/inscricoes'
    | '/login'
    | '/modalidades'
    | '/noticias'
    | '/reset-password'
    | '/sobre'
    | '/transparencia'
    | '/noticias/$id'
    | '/admin/banner'
    | '/admin/categorias-modalidades'
    | '/admin/diretores'
    | '/admin/eventos'
    | '/admin/eventos-pdfs'
    | '/admin/filiacoes'
    | '/admin/mensagens'
    | '/admin/modalidades'
    | '/admin/noticias'
    | '/admin/transparencia'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/eventos'
    | '/filie-se'
    | '/inscricoes'
    | '/login'
    | '/modalidades'
    | '/noticias'
    | '/reset-password'
    | '/sobre'
    | '/transparencia'
    | '/noticias/$id'
    | '/admin/banner'
    | '/admin/categorias-modalidades'
    | '/admin/diretores'
    | '/admin/eventos'
    | '/admin/eventos-pdfs'
    | '/admin/filiacoes'
    | '/admin/mensagens'
    | '/admin/modalidades'
    | '/admin/noticias'
    | '/admin/transparencia'
    | '/admin/usuarios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contato'
    | '/eventos'
    | '/filie-se'
    | '/inscricoes'
    | '/login'
    | '/modalidades'
    | '/noticias'
    | '/reset-password'
    | '/sobre'
    | '/transparencia'
    | '/noticias/$id'
    | '/_authenticated/admin/banner'
    | '/_authenticated/admin/categorias-modalidades'
    | '/_authenticated/admin/diretores'
    | '/_authenticated/admin/eventos'
    | '/_authenticated/admin/eventos-pdfs'
    | '/_authenticated/admin/filiacoes'
    | '/_authenticated/admin/mensagens'
    | '/_authenticated/admin/modalidades'
    | '/_authenticated/admin/noticias'
    | '/_authenticated/admin/transparencia'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  EventosRoute: typeof EventosRoute
  FilieSeRoute: typeof FilieSeRoute
  InscricoesRoute: typeof InscricoesRoute
  LoginRoute: typeof LoginRoute
  ModalidadesRoute: typeof ModalidadesRoute
  NoticiasRoute: typeof NoticiasRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SobreRoute: typeof SobreRoute
  TransparenciaRoute: typeof TransparenciaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modalidades': {
      id: '/modalidades'
      path: '/modalidades'
      fullPath: '/modalidades'
      preLoaderRoute: typeof ModalidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricoes': {
      id: '/inscricoes'
      path: '/inscricoes'
      fullPath: '/inscricoes'
      preLoaderRoute: typeof InscricoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filie-se': {
      id: '/filie-se'
      path: '/filie-se'
      fullPath: '/filie-se'
      preLoaderRoute: typeof FilieSeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$id': {
      id: '/noticias/$id'
      path: '/$id'
      fullPath: '/noticias/$id'
      preLoaderRoute: typeof NoticiasIdRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/transparencia': {
      id: '/_authenticated/admin/transparencia'
      path: '/admin/transparencia'
      fullPath: '/admin/transparencia'
      preLoaderRoute: typeof AuthenticatedAdminTransparenciaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/noticias': {
      id: '/_authenticated/admin/noticias'
      path: '/admin/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AuthenticatedAdminNoticiasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/modalidades': {
      id: '/_authenticated/admin/modalidades'
      path: '/admin/modalidades'
      fullPath: '/admin/modalidades'
      preLoaderRoute: typeof AuthenticatedAdminModalidadesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/mensagens': {
      id: '/_authenticated/admin/mensagens'
      path: '/admin/mensagens'
      fullPath: '/admin/mensagens'
      preLoaderRoute: typeof AuthenticatedAdminMensagensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/filiacoes': {
      id: '/_authenticated/admin/filiacoes'
      path: '/admin/filiacoes'
      fullPath: '/admin/filiacoes'
      preLoaderRoute: typeof AuthenticatedAdminFiliacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/eventos-pdfs': {
      id: '/_authenticated/admin/eventos-pdfs'
      path: '/admin/eventos-pdfs'
      fullPath: '/admin/eventos-pdfs'
      preLoaderRoute: typeof AuthenticatedAdminEventosPdfsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/eventos': {
      id: '/_authenticated/admin/eventos'
      path: '/admin/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AuthenticatedAdminEventosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/diretores': {
      id: '/_authenticated/admin/diretores'
      path: '/admin/diretores'
      fullPath: '/admin/diretores'
      preLoaderRoute: typeof AuthenticatedAdminDiretoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/categorias-modalidades': {
      id: '/_authenticated/admin/categorias-modalidades'
      path: '/admin/categorias-modalidades'
      fullPath: '/admin/categorias-modalidades'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasModalidadesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/banner': {
      id: '/_authenticated/admin/banner'
      path: '/admin/banner'
      fullPath: '/admin/banner'
      preLoaderRoute: typeof AuthenticatedAdminBannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminBannerRoute: typeof AuthenticatedAdminBannerRoute
  AuthenticatedAdminCategoriasModalidadesRoute: typeof AuthenticatedAdminCategoriasModalidadesRoute
  AuthenticatedAdminDiretoresRoute: typeof AuthenticatedAdminDiretoresRoute
  AuthenticatedAdminEventosRoute: typeof AuthenticatedAdminEventosRoute
  AuthenticatedAdminEventosPdfsRoute: typeof AuthenticatedAdminEventosPdfsRoute
  AuthenticatedAdminFiliacoesRoute: typeof AuthenticatedAdminFiliacoesRoute
  AuthenticatedAdminMensagensRoute: typeof AuthenticatedAdminMensagensRoute
  AuthenticatedAdminModalidadesRoute: typeof AuthenticatedAdminModalidadesRoute
  AuthenticatedAdminNoticiasRoute: typeof AuthenticatedAdminNoticiasRoute
  AuthenticatedAdminTransparenciaRoute: typeof AuthenticatedAdminTransparenciaRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminBannerRoute: AuthenticatedAdminBannerRoute,
  AuthenticatedAdminCategoriasModalidadesRoute:
    AuthenticatedAdminCategoriasModalidadesRoute,
  AuthenticatedAdminDiretoresRoute: AuthenticatedAdminDiretoresRoute,
  AuthenticatedAdminEventosRoute: AuthenticatedAdminEventosRoute,
  AuthenticatedAdminEventosPdfsRoute: AuthenticatedAdminEventosPdfsRoute,
  AuthenticatedAdminFiliacoesRoute: AuthenticatedAdminFiliacoesRoute,
  AuthenticatedAdminMensagensRoute: AuthenticatedAdminMensagensRoute,
  AuthenticatedAdminModalidadesRoute: AuthenticatedAdminModalidadesRoute,
  AuthenticatedAdminNoticiasRoute: AuthenticatedAdminNoticiasRoute,
  AuthenticatedAdminTransparenciaRoute: AuthenticatedAdminTransparenciaRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface NoticiasRouteChildren {
  NoticiasIdRoute: typeof NoticiasIdRoute
}

const NoticiasRouteChildren: NoticiasRouteChildren = {
  NoticiasIdRoute: NoticiasIdRoute,
}

const NoticiasRouteWithChildren = NoticiasRoute._addFileChildren(
  NoticiasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ContatoRoute: ContatoRoute,
  EventosRoute: EventosRoute,
  FilieSeRoute: FilieSeRoute,
  InscricoesRoute: InscricoesRoute,
  LoginRoute: LoginRoute,
  ModalidadesRoute: ModalidadesRoute,
  NoticiasRoute: NoticiasRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SobreRoute: SobreRoute,
  TransparenciaRoute: TransparenciaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
